name: SIT CD

on:
  repository_dispatch:
    types: [dast-testing-repository-dispatch]

jobs:
  zap_scan:
    # runs-on: ubuntu-latest
    runs-on: self-hosted:sit
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://ais-sit.azurewebsites.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          fail_action: true